#!/usr/bin/env bash

# until you no longer have "rebinding lease" ad infinitum,
# remove the file this bug [1]  so kindly pointed out:
# [1] http://bugs.archlinux.org/task/23282
rm -v /var/lib/dhcpcd/dhcpcd-*.lease
