#!/usr/bin/env bash
# inverse of `seated` script
set -euo pipefail
source ~/bin/share/zacsh_exports
punchDir="$(dirname "$(readlink -f "$(type -p punch)")")"; declare -r punchDir
"$punchDir"/screen_sleep out
