#!/usr/bin/env bash
#
# Things that all the machines I use for drupal dev. will need.
# @see ~/.host/pick

if [[ $(declare -p PROJECT_BASE)]];then

    #@TODO: figure out a way to re-work all of this to base off dynamic
    # bash functions, calling things like `git rev-parse --show-toplevel` and `hg root`

    [[ $(declare -p CB) ]] && declare -a CB
    export CB+=(${PROJECT_BASE}/sites/all/modules/{features,custom})
fi

#
# include your drupal shell utilities in your path.
#
export PATH=$PATH:~/usr/local/bin/drupalsh

#
# one-liners that I can't bear to see as a seperate script.
#

#@TODO: remove me once i've been solved in github.com/jzacsh/drupalsh/drupalsh +/pfetch
alias pfetch='time { drush cc all && drush -y fra && drush -y cc all && drush -y updb && hg push && hg stat; }'


#@TODO: can/should these be abstracted for public use, at all?
f() { ge ${@} $CB ; }
fs() { fstuff ${@} --exclude-dir='.hg' --exclude='.git'; }
