#!/bin/bash
#
# System package manager is bypassed for a LOT of things. It's good to have
# something automatically check those other bypassing channels periodically and
# let myself know.
#
# NOTE: the AIs produced by this script probably involve a lot of research and
# annoying investigation, so don't run this if you're unlikely to be able to act
# (e.g. if you're in a tty without a desktop environment).


log_jzdots info 'checking for AIs from non-system package managers...\n'

haveBin() ( type "$1" >/dev/null 2>&1; )

if haveBin go; then
  ~/.host/common/sideload-check-golang.ts ||
      log_jzdots warn 'side-loader: golang version is outdated\n'
fi

# TODO(jzacsh) write something for `deno` bin; eg:
#  Refactor ~/.host/common/sideload-check-golang.ts to pull out its core logic,
#  so as to utilize this JSON output:
#     curl   -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/denoland/deno/releases

if haveBin rustup; then
  log_jzdots info 'checking rustlang `rustup`...\n'
  rustup update --no-self-update ||
      log_jzdots err 'side-loader: `rustup update` update failed\n'
fi

# TODO(jzacsh) rclone version checker to compare:
# their for repo in ~/media/src/rclone `git tag --list` output
# against `rclone version` output
# https://rclone.org/install/#install-from-source

unset haveBin
