#!/bin/bash


# TODO this is still experimental; no idea if DBUS_SESSION_BUS_ADDRESS is
# really a reliable signal; not sure _which_ signals are really reliable.
# just trying to make sure i don't see useless errors when i login via SSH
# and/or a seated TTY
is_desktop_env() (
  [[ -n "$DISPLAY" ]] && [[ -n "$DBUS_SESSION_BUS_ADDRESS" ]]
)

get_desktop_env() (
  local deEnv="$DE"
  [[ -n "$DE" ]] || deEnv="$DESKTOP_SESSION"
  echo "$deEnv"
)

# useful catalog of some env. variables in this space:
#   https://wiki.archlinux.org/index.php/Environment_variables#Examples
is_known_desktop_env() (
  is_desktop_env && [[ -n "$(get_desktop_env)" ]]
)

src_this() {
  local target="$1"
  if ! [[ -f "$target" ]] || ! [[ -r "$target" ]];then
    local col_ylw='\e[0;33m' col_end='\033[0m'
    local t; printf -v t '%s%s' "${target/$HOME\/}"
    local logPrefix="$col_ylw"'WARNING'"$col_end"
    printf \
      "$logPrefix"': ~/%-15s not readable file\n' \
      "$t" >&2
    return # don't error return; don't want to stop my own shell login
  fi
  source "$target"
}

src_all() {
    local prefix dir; dir="$HOME/.host"

    #
    # generic distro-specific config
    #
    prefix="$dir"/distro.
    if [[ -f /etc/arch-release ]]; then
        src_this "${prefix}arch"
    elif [[ -f /etc/lsb-release ]]; then
        deb_dist_file=${prefix}$(awk -F'=' '/^DISTRIB_ID/{print tolower($2)}' /etc/lsb-release)
        src_this "$deb_dist_file"
    fi

    #
    # host-specific configuration
    #
    local hostfile; hostfile="$dir/host.${HOSTNAME/.*/}" #mimic `hostname -s`
    src_this "$hostfile"

    #
    # DE(GUI)-specific configuration
    #
    if is_known_desktop_env;then
      deEnv="$(get_desktop_env)"
      prefix="$dir"/deskenv.
      src_this "${prefix}${deEnv}"
    fi

    #
    # domain-specific configuration
    #
    src_this "$dir/domain.$(hostname --domain)"
}

src_all
unset src_all src_this
