#!/bin/bash

# host-specific configuration

dir="~/.host"
hostfile="$dir/$HOSTNAME"
if [[ -f $hostfile ]]; then 
  source $hostfile
else
  #fall back on general distro-only config
  if [[ -f /etc/arch-release ]]; then
     [[ -f $dir/distro.arch ]] && source $dir/distro.arch
  elif [[ -f /etc/lsb-release ]]; then
    deb_distro=$dir/distro.$(awk -F'=' '/^DISTRIB_ID/{print tolower($2)}' /etc/lsb-release)
    [[ -f $deb_distro ]] && source $deb_distro
  fi
fi

echo "DISTRO=$distro"
