#!/usr/bin/env bash
#
# Local mail unread counter badge, intended for i3blocks(1)
mail -H >/dev/null 2>&1 || exit 0

declare -r count=$(mail -H 2>&1 | wc -l)

declare -r plural="$(if [ $count != 1 ]; then printf S;fi)"
printf '%s MAIL%s\n%s' "$count" "$plural" "$count"
